language: R
latex: false
cache: packages

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran"

matrix:
  include:
    - os: osx
    - os: linux
      before_install: sudo apt-get install -y libx11-dev mesa-common-dev libglu1-mesa-dev libgsl-dev