language: R
r:
  - release
  - devel
latex: false
fortran: false
cache: packages
os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install mesa-common-dev; fi