language: R
latex: false
cache: packages

env:
  global: RGL_USE_NULL=TRUE

matrix:
  include:
    - os: osx
    - os: linux
      before_install:
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install mesa-common-dev; fi
        - wget -O travis_helpers.sh http://bit.ly/travis_helpers
        - source travis_helpers.sh
        - rm travis_helpers.sh
        - PACKAGE_NAME=`package_name`
        - PACKAGE_DIRECTORY=`basename ${PWD}`






